### ISSUE TITLE
Inconsistent Tags

### ISSUE THREAD

**Issue by elliotsayes** [permaweb/vouch-x#7]
Key and Value are both different here, not sure which is correct

https://github.com/permaweb/vouch-x/blob/06cb364dec860620e74ff49ea0e9ae839bb19f90/server/lib/is-vouched.js#L11
https://github.com/permaweb/vouch-x/blob/06cb364dec860620e74ff49ea0e9ae839bb19f90/server/lib/dispatch.js#L16

**Comment by twilson63** [comment]
Dispatch is legacy Vouch Version
is-vouched is using new vouch schema

***@***.***/r13cgYWlC?type=view

**Comment by elliotsayes** [comment]
Thanks! I'll see if I can support all 👍

**Comment by elliotsayes** [comment]
Wait-- are these supposed to be the same then? It seems like the format in `is-vouched` doesn't match up with any of them 
https://github.com/permaweb/vouch-x/blob/06cb364dec860620e74ff49ea0e9ae839bb19f90/server/lib/is-vouched.js#L9
https://github.com/permaweb/vouch-x/blob/06cb364dec860620e74ff49ea0e9ae839bb19f90/server/lib/send-message.js#L11

**Comment by twilson63** [comment]
Yep, that is a bug in `is-vouched` it should be `{ name: 'Data-Protocol', values: ['Vouch'] }, `

according to the spec

**Comment by elliotsayes** [comment]
Cool thanks!
